# Generated by Django 5.1.4 on 2024-12-31 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UserStory', 'User Story'), ('Incident', 'Incident'), ('Bug', 'Bug'), ('Task', 'Task')], max_length=50)),
                ('backlog_count', models.IntegerField(default=0)),
                ('month', models.DateField()),
                ('year', models.IntegerField()),
            ],
            options={
                'unique_together': {('type', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('UserStory', 'User Story'), ('Incident', 'Incident')], max_length=50, null=True)),
                ('total_items', models.IntegerField()),
                ('closed_items', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Delivery Progress',
                'verbose_name_plural': 'Delivery Progresses',
                'unique_together': {('month', 'year', 'type')},
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value for the KPI.', max_digits=15)),
                ('metric_type', models.CharField(choices=[('percentage', 'Percentage'), ('currency', 'Currency'), ('count', 'Count')], default='count', help_text='Type of metric (e.g., %, R$, count).', max_length=50)),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Current calculated value.', max_digits=15)),
                ('work_item_type', models.CharField(blank=True, choices=[('Task', 'Task'), ('Bug', 'Bug'), ('UserStory', 'User Story'), ('Incident', 'Incident')], max_length=50, null=True)),
                ('start_date', models.DateField(help_text='Start date of the KPI period.')),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('calculated_date', models.DateField(auto_now=True, help_text='Last calculation date.')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['-start_date', 'name'],
                'unique_together': {('name', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('UserStory', 'User Story'), ('Incident', 'Incident')], max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('changed_date', models.DateField()),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'indexes': [models.Index(fields=['type'], name='dashboard_w_type_7a2a2b_idx'), models.Index(fields=['state'], name='dashboard_w_state_02fae9_idx'), models.Index(fields=['created_date'], name='dashboard_w_created_51b35e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkItemSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('UserStory', 'User Story'), ('Incident', 'Incident')], max_length=50)),
                ('total_count', models.IntegerField(default=0)),
                ('average_lead_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('closed_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rework_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'unique_together': {('type', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WorkItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('changed_date', models.DateField()),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.workitem')),
            ],
            options={
                'verbose_name': 'Work Item History',
                'verbose_name_plural': 'Work Item Histories',
                'indexes': [models.Index(fields=['changed_date'], name='dashboard_w_changed_2baf37_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkItemReopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reopen_count', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_history', to='dashboard.workitem')),
            ],
            options={
                'verbose_name': 'Work Item Reopen',
                'verbose_name_plural': 'Work Item Reopens',
                'unique_together': {('work_item', 'created_date')},
            },
        ),
    ]
